# docker build -t tms:latest .
# docker run -p 3000:3000 --env-file ./config/config.env --name tms-container --rm tms:latest

services:
  backend:
    build: ./
    ports:
      - "3000:3000"
    image: "tms:latest"
    env_file:
      - ./config/config.env
# Run this:
# Navigate to this directory
# > docker-compose up
# Stop this:
# > docker-compose down
# View all containers
# > docker ps -a
